### ISSUE TITLE
integration: pinecone

### ISSUE THREAD

**Issue by Nasfame** [learnery-engine/api.creator.learnery#27]
TODO:

- [ ]  Write unit tests
- [ ] Write pinecone service methods
- [ ]  Write health check methods
- [ ] Write configs

**Comment by mhasif0786** [comment]
Hi @Nasfame , 

Can we talk overcall to understand code structure ?

**Comment by Nasfame** [comment]
Sure but I have already left the code structure in the pr.

**Comment by Nasfame** [comment]
Done #47
